# Generated by Django 4.1.2 on 2023-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0011_remove_connectfourgame_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectfourgame',
            name='board',
            field=models.JSONField(default=[[' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' '], [' ', ' ', ' ', ' ', ' ', ' ', ' ']]),
        ),
    ]
