# Generated by Django 4.1.2 on 2023-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0012_connectfourgame_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectfourgame',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
